#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'twoStacks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER maxSum
#  2. INTEGER_ARRAY a
#  3. INTEGER_ARRAY b
#
def twoStacks(maxSum, a, b):
    count=0
    sum1=0
    while count<len(a) and sum1+a[count] <= maxSum:
        sum1+=a[count]
        count+=1
    max_count=count 
    for i in range(len(b)):
        sum1+= b[i]
        while sum1> maxSum and count> 0:
            count-=1
            sum1-= a[count]
        if sum1 <= maxSum:
            max_count = max(max_count, count+i+1)
    return max_count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    g=int(input().strip())

    for g_itr in range(g):
        first_multiple_input=input().rstrip().split()

        n=int(first_multiple_input[0])

        m=int(first_multiple_input[1])

        maxSum=int(first_multiple_input[2])

        a=list(map(int,input().rstrip().split()))

        b=list(map(int,input().rstrip().split()))

        result=twoStacks(maxSum,a,b)

        fptr.write(str(result)+'\n')

    fptr.close()
